// Generated by genver.exe
// Created: 2023-05-26 07:44:30 CEST
package main

import (
	"fmt"
	"os"
)

const (
    version string = "v1.0.0"
    gitcommit string = "v1.0.0"
)

func ShowVersionOnly() {
    fmt.Fprintf(os.Stdout, "version: %s\n", version)
    os.Exit(0)
}

func ShowVersion() {
    fmt.Fprintf(os.Stdout, "version: %s (%s)\n", version, gitcommit)
    os.Exit(0)
}